name: "AI Team Orchestrator"
description: "Equipe d'agents IA qui code automatiquement pour vous via une interface simple"
author: "AI Team"
version: "1.0.0"

# URL de l'app (sera votre domaine ou service gratuit comme Vercel/Netlify)
url: "https://ai-team-orchestrator.vercel.app"
webhook_url: "https://ai-team-orchestrator.vercel.app/api/webhook"

# Permissions nécessaires
default_permissions:
  contents: write
  issues: write
  pull_requests: write
  metadata: read

# Événements que l'app écoute
default_events:
  - installation
  - installation_repositories

# Configuration pour GitHub Marketplace
public: true
categories:
  - "Code Quality"
  - "Productivity"
  - "Project Management"

# Screenshots et assets (optionnel)
logo: "assets/logo.png"
screenshots:
  - "assets/screenshot1.png"
  - "assets/screenshot2.png"

# Instructions d'installation
setup_instructions: |
  1. Installez l'app sur votre repository
  2. Configurez vos tokens IA (Hugging Face/Groq) 
  3. Cliquez sur "AI Team" dans l'interface GitHub
  4. Décrivez votre tâche et choisissez votre agent
  5. Regardez l'IA créer le code automatiquement !

# Support
support_url: "https://github.com/your-repo/issues"
privacy_policy_url: "https://ai-team-orchestrator.vercel.app/privacy" 